In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.25.0
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
z=np.arange(1,10)
print(z)
print(z[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [6]:
z=np.arange(1,10).reshape(3,3)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
z=np.random.random((10,10))
print(z)
print(z.min(),z.max())

[[0.06768454 0.31450958 0.71339789 0.2531909  0.86963281 0.69415462
  0.848435   0.65975302 0.38699385 0.57217418]
 [0.33610605 0.32664199 0.82402391 0.4339724  0.67374485 0.19623583
  0.76513767 0.43539506 0.17185077 0.95668273]
 [0.78954534 0.51508555 0.66316126 0.80323731 0.85173558 0.70930724
  0.16173558 0.47748028 0.58656604 0.99576788]
 [0.49866354 0.25058206 0.97711705 0.61801509 0.91023999 0.37013811
  0.66668244 0.0295355  0.48219515 0.96372558]
 [0.67852558 0.72342351 0.56009571 0.22857425 0.56002266 0.94193224
  0.85363213 0.78717439 0.42877326 0.79107736]
 [0.59937131 0.95384325 0.41093478 0.2789132  0.9536516  0.56247793
  0.71725239 0.98852946 0.45920108 0.91293387]
 [0.70271185 0.62210712 0.92122541 0.52665622 0.51331877 0.70319728
  0.53230894 0.01203702 0.58962165 0.30200113]
 [0.37015501 0.34239105 0.52076171 0.34118539 0.24269944 0.9283241
  0.84191938 0.85104002 0.63732187 0.59421715]
 [0.91933195 0.31021379 0.99197293 0.69811153 0.76343044 0.86924944
  0.7764021  

In [9]:
z=np.random.random(30)
m=z.mean()
print(m)

0.578470203107733


In [10]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [11]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\Tarun\AppData\Local\Temp\ipykernel_15104\889307967.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


In [13]:
import numpy as np

In [14]:
arr=[1,2,3,4,5]
arr[-1]=10
print(arr)
print(type(arr))

[1, 2, 3, 4, 10]
<class 'list'>


In [15]:
arr=np.array(arr)
print(type(arr))

<class 'numpy.ndarray'>


# using the tuple to creating array

In [16]:
arr2=(1,2,3,4,5)
print(type(arr2))
print(arr2[-1])

<class 'tuple'>
5


In [17]:
arr2=np.array((arr2))
print(type(arr2))

<class 'numpy.ndarray'>


In [18]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [19]:
print(a.ndim,
b.ndim,
c.ndim,
d.ndim)

0 1 2 3


# creating n dimension array

In [20]:
s=np.array([1,2,3],ndmin=4)
print(s,s.ndim)

[[[[1 2 3]]]] 4


# Accesing the numpy elements

In [21]:
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3[0,1])

2


In [22]:
arr4=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr4[1,1,2])


12


# here on above the 1st element represents the index of arr 2nd element represents inside the index of arr 3rd element represents the element

# slicing of arrys

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0:5])
print(-arr[3:-3])

[1 2 3 4 5]
[-4]


In [24]:
print(arr[1:5:2])
# here the last elements is called step

[2 4]


In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])

[7 8 9]


# checking the data type of arr

In [26]:
print(arr.dtype)

int32


In [27]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [28]:
# creating the elements with dtype
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

|S1


# converting one dtype to another dtype

In [29]:
arr.astype('O')
print(arr)

[b'1' b'2' b'3' b'4']


In [30]:
arr.astype(bool)

array([ True,  True,  True,  True])

# difference between the copy and view
# The copy SHOULD NOT be affected by the changes made to the original array.
# But,the view SHOULD be affected by the changes made to the original array.

In [31]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 42
print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


# As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

# Every NumPy array has the attribute base that returns None if the array owns the data.

# Otherwise, the base  attribute refers to the original object.

In [33]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr.shape

(2, 4)

In [35]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
arr.shape

[[[[[1 2 3 4]]]]]


(1, 1, 1, 1, 4)

In [36]:
# Reshaping means changing the shape of an array.
arr=[[1,2,3,4,5,6]]
arr=np.array(arr)
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [38]:
# flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-2)

print(newarr)

[1 2 3 4 5 6]


In [39]:
# iterating the array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [40]:
# using the enumearate like loop
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


# Joining means putting contents of two or more arrays in a single array.

# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2),axis=0)

print(arr)


[1 2 3 4 5 6]


In [42]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

In [43]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [45]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


# we can also split the arrays into many parts

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [49]:
# finding the elements we use where and search sorted
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [50]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


# we can search the elements either right or left

In [51]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
y=np.searchsorted(arr, 7, side='left')

print(x)
print(y)

2
1


In [52]:
# calling the random number integer type
from numpy import random

x = random.randint(100)

print(x)

62


In [53]:
# calling the float
from numpy import random

x = random.rand()

print(x)

0.06581372233783156


In [54]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

[28 60 21 41 88]


In [55]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 5 5 3]
 [7 3 9 9 9]
 [3 3 5 9 5]]


In [56]:
def myadd(x, y):
  return x+y
myadd=np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


# arthematic,subtraction,multiplication, division etc

In [57]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [58]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [59]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [60]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [61]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [62]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [63]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [64]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [65]:
# rounding the decimals
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [66]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)


[-3.  3.]


In [67]:
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [68]:
arr = np.around(3.1666, 2)

print(arr)

3.17


In [69]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [70]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)


12


In [71]:
# using the set which is called unique
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [72]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [73]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [74]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]
